Fix #20 - Error: 'NoneType' object has no attribute 'has_section'
The error was improperly handling the scenario where a profile
configuraiton doesn't exist.  Since the only branch where this can occur
requires profiles are set, the more appropriate behavior is to raise a
useful exception instead of setting a dummy value.